version: '3.3'

volumes:
  pg_data:

services:

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django_password
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: nginx:1.19.3
    container_name: nginx_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app





